title: su's dev portfolio
name: SU KIM
email: rlatn216@naver.com
description: >-
  Android Developer


baseurl: ""
url: "https://babycheetah.github.io"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
facebook_id: babycheetah
github_id: rlatn216


# Youtube vid
youtube_vid: #


# Custom Color
primary: 0B0719 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: CF94D8 #b72cf0
color_2: CF94D8
color_3: CF94D8
color_4: CF94D8
color_5: CF94D8
color_6: CF94D8


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_3.jpg
  title: Welcome <br>To My </br> Portfolio </br>


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/img_bg_4.jpg
  title: Android<br> Developer
  subtitle: >- 
    Kotlin / Java<br>
    Web / Native / Hybrid APP<br>
    Compose<br>


# About
about_meta: About Me
about_header: >- 
  "도전이 없다면 성장도 없다"
about_introduce: >-
  "안녕하세요, 안드로이드 개발자 김수입니다."
about_content: >-
  저는 "도전이 없다면 성장도 없다"라는 좌우명을 가슴에 품고 새로운 것에 도전하며 성장하는 개발자입니다. </br>
  소프트웨어 학과에서 IT의 기본 지식을 쌓았고, 학술 동아리 활동을 통해 작품 공모전, 아이디어 대회, 창업 대회 등 다양한 프로젝트에 참여하며 실전 경험을 쌓았습니다. </br>
  현재 금융계열 IT 회사에서 R&D를 통해 Android 개발 역량을 높히고 회사의 솔루션을 깊이 이해하기 위해 Android 앱뿐만 아니라 PC, 서버, 웹 등 직접개발을 진행해보며 종합적인 기술 이해도를 높였습니다. 
  또한, 여러 증권사에 파견되어 다양한 프로젝트를 수행하며 개발 능력과 이슈 대응 능력을 키웠습니다. </br>
  이처럼 끊임없는 도전과 목표 달성을 통해 지속적으로 성장하고 있으며, 조직에 필수적인 개발자가 되기 위해 최선을 다하고 있습니다. </br>
  앞으로도 새로운 도전을 통해 더 나은 개발자가 되겠습니다. </br>

about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: Kotlin
- icon: icon-code
  name: Java
- icon: icon-android
  name: Android
- icon: icon-settings
  name: Dev-Ops
# about_box_content: 괜찮은 문구 <br>박스 색바꾸는 yml파일에 추가 <br><br><br>야물파일로 변환 <strong>의뢰</strong>의뢰
# about_box_button:
#   link: #
#   name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: 
tech_list: # 형식에 맞추어 항목 추가
- name: Achitecture
  color: color-1
  animation: fadeInLeft
  percent: 50
  mark: 50
  content: MVVM 패턴을 현업에서 사용하여 전자문서를 통해 은행 업무가 가능한 디지털 창구서비스, 재사용성과 생산성을 높일 수 있게 표준화를 수행한 경험이 있습니다.
- name: Jetpack
  color: color-2
  animation: fadeInRight
  percent: 70
  mark: 70
  content: viewmodel, navigation, Repository, LiveData, stateFlow 등 jetpack에서 제공해주는 다양한 라이브러리를 사용하여 안드로이드 앱을 구현할 수 있습니다.
- name: DI
  color: color-3
  animation: fadeInLeft
  percent: 40
  mark: 40
  content: MVVM패턴에서 각 기능을 맡고있는 클래스에 의존성을 주입을 하기 위해 Hilt를 사용하여 의존성을 관리해본 경험이 있습니다.
- name: Networking
  color: color-4
  animation: fadeInRight
  percent: 50
  mark: 50
  content: API 통신을 위해 구현된 OkHttp의 HTTP 통신을 간편하게 해주는 Retrofit2, 태블릿과 pc 통신을 위한 구독형 통신 MQTT, 등을 사용해본 경험이 있습니다.
tech_desc: 항상 주어진 요구 사항에 맞게 원하는 기능을 개발할 준비가 되어있고 꾸준히 효율적인 아키텍처로 앱을 개발하는 법을 공부하고 있습니다.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_my_name: 프로젝트

project_my: # 형식에 맞추어 항목 추가
- background_url: images/personal_project1.png
  animation: fadeInLeft
  name: 스마트 전시회관람 앱
  description: NFC 태그를 활용하여 태그 스티커의 고유 ID마다 동영상을 매칭하여 DB에 저장해 지정된 태그에 영상이 표출될 수 있게 만든 프로젝트
  # detail_url: #
  readmore_url: https://github.com/rlatn216/Smart-Exhibition-app

- background_url: images/personal_project2.png
  animation: fadeInLeft
  name: 문자인식 번역 앱
  description: firebase의 ML-kit을 활용하여 스마트폰으로 영어가 보이는 곳을 사진으로 찍어 한국어로 번역하여 읽어주는 애플리케이션
  # detail_url: #
  readmore_url: https://github.com/rlatn216/Text-recognition-translation-app

- background_url: images/personal_project3.png
  animation: fadeInLeft
  name: 음성드론 조종앱
  description: STT(Speech to Text)를 사용해 사람의 음성을 Text로 변환 후 소켓 통신을 이용하여 드론에서 데이터 전송을 해주는 애플리케이션
  # detail_url: #
  readmore_url: https://github.com/rlatn216/Drone-app

# project_team_name: 팀프로젝트
# project_team: # 형식에 맞추어 항목 추가
# - background_url: images/team_project3.PNG
#   animation: fadeInRight
#   name: Anti-Drone_Robot(2020.05)
#   description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#   detail_url: #
#   readmore_url: #

# - background_url: images/team_project3.PNG
#   animation: fadeInRight
#   name: sasdasdasdsadsagjghkukt(2020.05)
#   description: 2019년 드론기술발전에 따른 드론관련 사고들이 많아지고 있음을 파악하고 그에따른 대처가 필요하다고 생각 하여 인공지능을 이용한 Anti Drone Robot 을 개발하였다
#   detail_url: #
#   readmore_url: #

# project_business_name: Business
# project_business: # 형식에 맞추어 항목 추가
# - background_url: images/my_business.PNG
#   animation: fadeInTop
#   name: 인프런강의(2021~)
#   description: >-
#     취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
#     또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
#     많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
#     공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
#   detail_url: #
#   readmore_url: #


# achievement
ach_meta: achievement
ach_header: achievement
ach_list:
# - title: KOREA UNIVERSITY ARTIFICIAL INTELLIGENCE MASTER'S DEGREE
#   subtitle: 고려대 인공지능학과 대학원 석사과정
#   date: 20xx.01 - 현재
#   content: 설명설명 설명글
- title: certificate
  ach_sublist:
    - subtitle: 정보처리기사
      date: 2022-09
      agency: 한국산업인력공단
      content: 정보처리기사 취득
- title: CONTEST
  ach_sublist:
    - subtitle: 장려상
      date: 2021-10
      agency: 대구대정보통신대학
      content: 2021학년도 정보통신대전 학생작품경진대회
    - subtitle: 입선상
      date: 2020-12
      agency: 인천테크노파크
      content: 인천 VR,AR 콘텐츠 아이디어 공모전
    - subtitle: 장려상
      date: 2020-11
      agency: 경상북도 LINC+사업단
      content: 2020 대학생 4차산업혁명 크리에이티브 공모전
    - subtitle: 우수상
      date: 2020-11
      agency: 청음복지관
      content: 제 1회 청각장애인 편의증진을 위한 ICT아이디어 공모전
    - subtitle: 입선상
      date: 2019-12
      agency: 한국정보산업연합회
      content: 2019 한이음 공모전
    - subtitle: 장려상
      date: 2019-12
      agency: 충북 ICT산업
      content: 2019 ICT융합 공모전
    - subtitle: 장려상
      date: 2019-12
      agency: 로보링크 주식회사
      content: 제 1회 코드론 창작 콘테스트
    - subtitle: 장려상
      date: 2019-11
      agency: 대구대학교
      content: 교내 SW아이디어 챌린지 공모전
    - subtitle: 우수상
      date: 2019-11
      agency: 공학교육혁신협회
      content: 2019 공학교육페스티벌
    - subtitle: 창의상
      date: 2019-10
      agency: 대구대학교 공학교육혁신센터
      content: 교내 DU Creative Festival 창의아이디어 경진대회
    - subtitle: 입상
      date: 2019-10
      agency: 대구대학교 공학교육혁신센터
      content: 교내 DU Creative Festival 캡스톤디자인 경진대회
    - subtitle: 우수작품상
      date: 2019-10
      agency: 한국산업융합학회
      content: 2019 창원전국지능로봇경진대회
    - subtitle: 장려상
      date: 2016-11
      agency: 경북창조경제혁신센터
      content: 제 4회 G-Star 대학생 창업경진대회
    - subtitle: 장려상
      date: 2016-10
      agency: 대구대학교 창업지원단
      content: 교내 DU 청춘 아이디어 경진대회
    - subtitle: 우수상
      date: 2016-10
      agency: 대구대학교 정보통신대학
      content: 교내 2016 공학제 작품전시회
    - subtitle: 우수기능상
      date: 2016-08
      agency: 한국산업융합학회
      content: 2016 전국지능로봇경진대회
    - subtitle: 장려상
      date: 2016-06
      agency: 대구대학교 공학교육혁신센터
      content: 2016 즐기는 디자인창의융합캠프 장려상


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 문제해결능력
  color: color-1
  icon: icon-bulb
  content: 다양한 증권사 프로젝트 구축 및 기존 디지털 창구 모듈화를 진행하는 과정을 통해 문제 해결역량을 향상시켰습니다.
- name: 기술적응력
  color: color-2
  icon: icon-home
  content: 프로젝트 참가 이력이 많아 여러 기술들을 접할 기회가 많았기에 항상 새로운 마음으로 배워왔습니다. 최근에는 금융IT에서 compose를 활용한 안드로이드 개발을 이어가고 있습니다.
- name: 기술성장
  color: color-3
  icon: icon-phone3
  content: 다양한 분야의 공모전에 참여하며 사용자의 편의성과 사업성을 모두 잡을 수 있는 아이디어를 위해 IT 기술에 꾸준히 관심을 갖고 적용해보고자 노력하였습니다.
exp_counters:
- name: Online Class Sales
  count: 344
  speed: 10000
- name: project
  count: 6
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 인지소프트(금융 IT기업) 근무
  date: 2022.12 ~ 현재
  content: <ul>
  <li>PC Viewer와 Tablet 간의 MQTT구독형 통신 모듈 개발</li>
  <li>유진투자증권 PPR 솔루션 전자서식, 비즈로직 작성</li>
  <li>IBK 증권 ODS APP 전자문서 컨트롤 추가 개발 및 유지보수</li>
  <li>하나증권 ODS APP 개발 및 유지보수</li>
  </ul>
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
# - name: Voice Caddie 산학과제
#   date: 2021.05~2021.10
#   content: 현재 골프치는 사람의 Pose와 Multi-view를 연구하고 있습니다.
#   color: color-2
#   icon: icon-pen2
#   animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
# - title: KOREA UNIVERSITY ARTIFICIAL INTELLIGENCE MASTER'S DEGREE
#   subtitle: 고려대 인공지능학과 대학원 석사과정
#   date: 20xx.01 - 현재
#   content: 설명설명 설명글 
- title: DEAGU UNIVERSITY
  subtitle: 2016.03 - 2022.02
  content: 대구대학교 컴퓨터 소프트웨어학과 졸업
- title: JINLYANG HIGH SCHOOL
  subtitle: 2013.03 - 2016.02
  content: 진량고등학교


# # Blog
# blog_meta: self-improvement
# blog_header: BLOG and YOUTUBE
# blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
# blog_load_more_url: #
# blog_list:
# - title: 아기치타의 AI 대학원 블로그
#   subtitle: 개발 블로그 운영
#   date: 2021.01
#   content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해오고 있습니다.
#   thumbnail_url: images/blog-1.PNG
#   link: #
# - title: 따라쟁이의 유튜브
#   subtitle: 개발,논문 유튜브 채널 운영
#   date: 2018.04
#   content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
#   thumbnail_url: images/blog-2.PNG
#   link: #
# - title: 네이버블로그
#   subtitle: 이전 블로그
#   date: 2018.03
#   content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
#   thumbnail_url: images/blog-3.PNG
#   link: #


# # Contact
# contact_meta: Get in Touch
# contact_header: Contact
# contact_list:
# - title: 이런것들도 손쉽게 고칠수 있게 만들어주세요
#   icon: icon-globe-outline
# - title: 주소
#   icon: icon-map
# - title: +82 10 xxxx xxxx
#   icon: icon-phone
# - title: 웹 주소
#   icon: icon-layers2
#   url: https://google.com
# contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
